apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kibernate.fullname" . }}
  labels:
    {{- include "kibernate.labels" . | nindent 4 }}
data:
  kibernate.yml: |
    {{- toYaml .Values.kibernate | nindent 4 }}
