apiVersion: v1
kind: Service
metadata:
  name: {{ include "kibernate.fullname" . }}
  labels:
    {{- include "kibernate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- $ports := list }}
    {{- range .Values.kibernate.instances }}
    {{- $ports = append $ports .link.listenPort }}
    {{- end }}
    {{- $ports = uniq $ports }}
    {{- range $p := $ports }}
    - port: {{ $p }}
      targetPort: {{ $p }}
      protocol: TCP
      name: port-{{ $p }}
    {{- end }}
  selector:
    {{- include "kibernate.selectorLabels" . | nindent 4 }}
