version: 0
instances:
  - name: default
    link:
      type: http
      listenPort: 8080
      servicePort: 8080
      serviceName: testtarget
    middlewares:
      - type: noneWaiter
    extensions: []
    controller:
      type: deployment
      namespace: default
      deployment: testtarget
      idleTimeout: 01:00:00